# Generated by Django 4.2.1 on 2023-07-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-id']},
        ),
    ]
