# Generated by Django 4.2.1 on 2023-07-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_snippet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='Male', max_length=255),
        ),
    ]
